name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true
      tag_ref:
        type: string
        required: false
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
      tag_ref:
        type: string
        required: false

jobs:
  test-empty:
    name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make the tag
      uses: ./.github/actions/tag
      with:
        tag_name: test-empty-tag
  test-with-sha:
    name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make the tag
      uses: ./.github/actions/tag
      with:
        tag_name: test-with-sha-tag
        tag_ref: ${{ github.sha }}
  test-with-branch:
    name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make the tag
      uses: ./.github/actions/tag
      with:
        tag_name: test-with-branch-tagh
        # This is a tag
        tag_ref: tests-will-break-if-deleted


