name: Make a tag
on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true
      tag_ref:
        type: string
        required: false
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
      tag_ref:
        type: string
        required: false

jobs:
  test:
    name: Make the tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make the tag
      uses: ./.github/actions/tag
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        tag_ref: ${{ github.event.inputs.tag_ref }}
