name: Update version reference
on:
  release:
    types: [edited, published]
jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract major version from tag
        id: major_version
        run: |
          FULL_VERSION=${GITHUB_REF##*/}
          MAJOR_VERSION=$(echo "${FULL_VERSION%.*.*}")
          echo "::set-output name=TAG_NAME::${MAJOR_VERSION}"
      - name: Update reference to latest version
        uses: ./
        with:
          tag_name: ${{ steps.major_version.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
